### PR TITLE
fix for inconsistencies in index for drawdown periods

### PR DESCRIPTION
**Pull request by thlautenschlaeger**

### CODE REVIEW

**Review by MBounouar — COMMENTED** [review]
I am curious to understand the context, because even if passed with a basic series like `pd.Series(np.array([0.0, -6.0, -7.0, -1.0, -9.0, -2.0, -6.0, -8.0, -5.0]) / 100)`
`get_max_drawdown_underwater`
and 
`valley = underwater.idxmin()`
work as expected.

`get_max_drawdown` function on the other hand ... is not working as describe in the docs ...

**Comment by thlautenschlaeger** [comment]
I am not able to reproduce it at the moment but in some cases the line
`valley = underwater.idxmin()`
assigns the integer position to valley instead of the datetime index. This assignment caused crashing when plotting the biggest drawdowns.
The crash happened at:
```
 df_drawdowns.loc[i, 'Valley date'] = (valley.to_pydatetime()
                                              .strftime('%Y-%m-%d'))
```
in timeseries.py in the method: **gen_drawdown_table()**

**Comment by MBounouar** [comment]
Then my 2cents would be that your PR  would just hide a potentially larger problem instead of resolving it.
My first guess would be that either the problem is coming from a bug in a version of pandas (check which version you are using ?), or something weird is happening in the background.
The original authors intended to deprecate all these functions in favor of the empyrical package functions. So it's not impossible that a few things have been overlooked.

**Comment by stefan-jansen** [comment]
Closing for now absent further activity.

**Pull request closed without merging**
